# Generated by Django 4.0.4 on 2022-05-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
