# Generated by Django 4.0.4 on 2022-05-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
