# Generated by Django 4.0.4 on 2022-05-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0007_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='user',
            new_name='owner',
        ),
    ]
